
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/shared/assets/css/globals.css";
import { ThemeProvider } from './provider';
import Script from 'next/script';
import { Toaster } from '@/shared/components/ui/sonner';
import TopBar from '@/shared/components/sections/TopBar';

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY;

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru" suppressHydrationWarning>
			<head>
				<Script
					src={`https://maps.googleapis.com/maps/api/js?key=${GOOGLE_API_KEY}&libraries=places`}
					strategy="beforeInteractive"
				/>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-y-auto`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					enableSystem
					disableTransitionOnChange
				>
					<TopBar />
					{children}
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}
